src/routes/Accounts/Accounts.tsx

padding will be improved as part of [IRO-2454](https://linear.app/ironfish/issue/IRO-2454/key-master-page)

(IRO-2364) Reduce spacing between icon and text.

---

src/routes/Onboarding/Action.tsx

https://linear.app/ironfish/issue/IRO-2413/heading-padding

(IRO-2412) (IR)-2413) Add padding and change headers size.

---

src/components/BackButtonLink.tsx
src/routes/Accounts/AccountDetails.tsx
src/routes/Accounts/Accounts.tsx
src/routes/AddressBook.tsx
src/routes/AddressDetails/AddressDetails.tsx
src/routes/AddressDetails/AddressTransactions.tsx
src/routes/Miner.tsx
src/routes/Send/Send.tsx
src/routes/Send/SendFlow.tsx

Style fixes

---

src/routes/Accounts/AccountTabs/Overview.tsx
src/routes/AddressBook/AddressBook.tsx
src/routes/AddressBook/AddressDetails/AddressTransactions.tsx

For address book `Frankie Boy` has transactions

Align transaction view details button.

---

src/components/AccountBalance.tsx
src/hooks/transactions/useFee.ts
src/routes/Send/Send.tsx

Added loading state to fee field.

Changed fee to estimated fee.

---

electron/ironfish/IronFishManager.ts
src/components/ContactsAutocomplete.tsx
src/components/Navbar/ActiveStatus.tsx
src/data/DemoNodeManager.ts
src/routes/Send/SendFlow.tsx

https://airtable.com/appIXmGgVqP9QdbCf/tblAWSTOQbTq6vh6X/viwDHZiWCwtbVXlQ1/recm4IhbGo0dyap6w?blocks=hide

Added add contact to send flow.

---

src/components/EmptyOverview.tsx
src/hooks/transactions/useTransactions.ts
src/routes/Accounts/AccountTabs/Overview.tsx
src/routes/Accounts/Accounts.tsx
src/routes/AddressBook/AddContactModal.tsx
src/routes/AddressBook/AddressBook.tsx
src/routes/AddressBook/AddressDetails/AddressTransactions.tsx

To test contact transactions add contact with address `pjqETg9UDzCmE9QSuWwrNO80NC9GNYtLWwyHhw0slynI1lRi9NS3BX_sD8yWtk7D` (demo`Primary account` address)

Added empty state and empty search result.

---

src/hooks/addressBook/useAddressBook.ts
src/routes/AddressBook/AddressBook.tsx

Fix for problem: When typing in address book search whole table re-renders.

Fix search behavior.

---

electron/dev/preload.ts
electron/ironfish/AccountManager.ts
electron/prod/preload.ts
package.json
src/data/DemoAccountsManager.ts
src/data/DemoDataManager.ts
src/hooks/accounts/useCreateAccount.ts
src/routes/Accounts/AccountTabs/Keys.tsx
src/routes/Onboarding/CreateAccount.tsx
src/routes/Onboarding/CreateAccount/CreateAccount.tsx
src/routes/Onboarding/CreateAccount/CreateStep.tsx
src/routes/Onboarding/CreateAccount/ValidateStep.tsx
src/withDemoData.ts
types/Account.ts
types/AccountCreateParams.ts
types/IronfishManager/IIronfishAccountManager.ts
yarn.lock

Show mnemonic phrase instead keys on account Keys tab.
Related PR in ui-kit https://github.com/iron-fish/ui-kit/pull/112

Use mnemonic phrase

---

src/components/SimpleTable.tsx
src/components/WalletCommonTable.tsx
src/routes/Accounts/AccountTabs/Overview/SearchTransactions.tsx
src/routes/AddressBook/AddressBook.tsx
src/routes/AddressBook/AddressDetails/AddressTransactions.tsx

https://www.figma.com/file/vwr2pTKsMD4bql68PFn9rm/Iron-Fish-UI-Kit-Final?node-id=1212-241&t=o7Pezn7iofWX0TrJ-0

Make carets look the same for all tables.

---

src/components/Snapshot/SnapshotDownloadModal.tsx
src/components/Snapshot/SnapshotStatusModal.tsx
src/data/DemoAddressBookManager.ts
src/routes/Accounts/AccountTabs/Settings.tsx
src/routes/AddressBook/AddContactModal.tsx
src/routes/Onboarding/CreateAccount/CreateStep.tsx
src/routes/Onboarding/CreateAccount/ValidateStep.tsx
src/routes/Onboarding/ImportAccount.tsx
src/routes/Send/SendFlow.tsx

Affected modals:
* create account
* import account
* remove account
* add contact
* download snapshot (removed icon)
* send transaction, send transaction result modal (removed icons)

(IFL-345) Use same size for button sin modals, remove icons.

---

electron/dev/index.ts
electron/ironfish/TransactionManager.ts
src/routes/Accounts/AccountTabs/Overview/SearchTransactions.tsx
src/routes/Transaction/TransactionOverview.tsx

Fix for https://github.com/iron-fish/wallet-app/issues/208

Show memo for send transactions, from to -> show to.

---

src/components/DetailsPanel.tsx
src/components/Navbar/NavItem.tsx
src/components/Navbar/StatusBar/StatusItem.tsx
src/components/Navbar/StatusBar/index.tsx
src/components/Navbar/index.tsx
src/components/ThemeToggle.tsx
src/routes/PageLayout.tsx

Side panel animation added.
Changed side panel now uses sticky positioning.
Top snapshot download message is now sticky.
Added small ScaleFade effect when page changing.

Added animation to side panel and page changing.

---

package.json
src/components/Navbar/StatusBar/WalletSyncStatus.tsx
src/providers/DataSyncProvider.tsx
yarn.lock

When we start our wallet and peer network is not ready or don't have peers now will be displayed status 'Connecting'.
In case if peer network is started and progress is less than 100% and syncer is not started, then will be displayed current progress istead of status
All other cases is work correct with previous implementation.

IFL-782 - Added new wallet status - 'Connecting'.

---

package.json

Set version to 1, QA pre-release.

Pre-Release-v1.0.0

---

electron/common/initLog.ts
electron/ironfish/SnapshotManager.ts
src/components/Navbar/StatusBar/SnapshotStatus.tsx
src/components/Navbar/StatusBar/index.tsx
src/components/Snapshot/SnapshotStatusModal.tsx
src/data/DemoSnapshotManager.ts
src/providers/DataSyncProvider.tsx
src/providers/SnapshotProvider.tsx
src/routes/SnapshotFlow.tsx
types/IronfishManager/IIronfishSnapshotManager.ts

Update snapshot download condition.
Check that snapshot could provide more than 30% of chain data.

(IFL-858) Update snapshot condition.

---

src/components/EmptyOverview.tsx
src/routes/Updates/Updates.tsx

(IFL-919) Add empty state for updates.

---

electron/contextBridge/AccountManagerContext.ts
electron/ironfish/AccountManager.ts
src/components/ContactsAutocomplete.tsx
src/components/SyncWarningMessage.tsx
src/components/TextFieldErrorMessage.tsx
src/components/WarningMessage.tsx
src/data/DemoAccountsManager.ts
src/hooks/accounts/usePublicAddressValidator.ts
src/routes/AddressBook/AddContactModal.tsx
src/routes/AddressBook/AddressDetails/AddressDetails.tsx
src/routes/AddressBook/AddressDetails/ContactSettings.tsx
src/routes/Send/Send.tsx
types/IronfishManager/IIronfishAccountManager.ts

For demo data only public address length is validated.
Added validation for adding contact to address book.
Added validation to send page.
Made validation consistent in all places.

(IFL-942) Add contact public address change validation.

---

electron/ironfish/TransactionManager.ts
src/data/DemoTransactionsManager.ts
types/Transaction.ts

Use common method from rpc to decode notes.
For address book transaction resolve transaction field first and check required info from there as some information is stored in notes and notes decoding takes most of time.

(IFL-910) Show all available transactions for contact.

---

electron/ironfish/AccountManager.ts

Adds a scan after the account is created

feat(ifl-891): scan transactions account creation

---

src/routes/Send/Send.tsx
src/routes/Send/SendFlow/ConfirmStep.tsx
src/routes/Send/SendFlow/DataPreviewLine.tsx

Implements [IFL-965](https://linear.app/if-labs/issue/IFL-965/update-send-card-ui) and [IFL-954](https://linear.app/if-labs/issue/IFL-954/balance-on-send-page)

(IFL-954) Send page updates.

---

src/routes/Accounts/Accounts.tsx

* Add a debounce for searching
* Update loading state to not check length
* Get rid of timer

fix(node-app): Fix search loading and empty states

---

forge.config.js
src/components/Navbar/StatusBar/NodeSyncStatus.tsx
src/data/DemoNodeManager.ts
src/routes/Accounts/AccountPreview.tsx
src/routes/Accounts/AccountTabs/Overview/Overview.tsx
src/routes/Accounts/Accounts.tsx

Render a warning per account card depending on the account's head and remove the global wallet sync status.

feat(node-app): Show account level sync status

---

forge.config.js
package.json
yarn.lock

Switch from making `zip`s of the app to `dmg` of app.

feat(ifl-1074): add macos build support for dmg

---

src/routes/Onboarding/CreateAccount/ValidateStep.tsx

chore: styling update for create account flow

---

electron/ironfish/AccountManager.ts

https://github.com/iron-fish/node-app/assets/5459049/b420c5a1-fbf2-4d8d-8985-225835fa684b

fix(node-app): Throw error if Bech 32 decoding fails

---

forge.config.js

We are using a cloud cert so the standard `electron-forge` signing mechanism will not work:
https://www.electronforge.io/guides/code-signing/code-signing-windows
This uses `postMake` hook from electron forge to sign the exe before it is published.
https://www.electronforge.io/configuration#postmake
This guide was used by @dguenther to get azure ready:
https://melatonin.dev/blog/how-to-code-sign-windows-installers-with-an-ev-cert-on-github-actions/
Tested by running on push:
```
D:\a\node-app\node-app\out\make\squirrel.windows\x64\RELEASES
D:\a\node-app\node-app\out\make\squirrel.windows\x64\Iron Fish Node App-1.0.3 Setup.exe
Manual Sign exe Stdout: trce: AzureSignTool.SignCommand[0]
Retrieving certificate ***.
trce: AzureSignTool.SignCommand[0]
Retrieved certificate ***.
trce: …
```

feat(ifl-956): codesigning via postMake hook on windows with AzureSignTool

---

.github/workflows/publish-prod.yaml

This was supposed to be merged with:
https://github.com/iron-fish/node-app/pull/326
But the changes got reverted during testing and I missed this file.

feat(ifl-956): gha commit

---

src/routes/Send/Send.tsx
src/utils/number.ts

feat(ifl-1038): change 0.0 iron to 0

---

src/routes/Send/Send.tsx

`youe` -> `your` is the main thing I want to fix, but while I was in there, I edited the grammar of that message slightly.

Fix typo noticed during demo in explanation of fees on txn send

---

electron/ironfish/IronFishManager.ts
src/components/ErrorMessagesModal.tsx
src/routes/Initializing.tsx

https://github.com/iron-fish/node-app/assets/5459049/033a7b66-d9e4-4cde-b1a3-300ff94a3e3e

feat(node-app): Show error modal if another node is running

---

src/components/Navbar/StatusBar/index.tsx

https://github.com/iron-fish/node-app/assets/26990067/4395bee5-c6d9-4d02-95f5-a664641b7482

chore(ifl-1104): turn off warn on unsynced accounts

---

src/components/Navbar/StatusBar/NodeSyncStatus.tsx

Color of yellow will be fixed in:
https://github.com/iron-fish/node-app/pull/330

chore(ifl-1103): renaming idle -> connected

---

src/routes/Account/Overview/Transactions/Transactions.tsx

Implements hover styles/minor design feedback.

fix: Light mode transaction row styles

---

electron/ironfish/AccountManager.ts

https://github.com/iron-fish/node-app/assets/5459049/5ec9a200-bc34-4d01-8896-da36f6c504cc

fix(node-app): Ensure `id` is defined when importing JSON file

---

src/routes/Onboarding/ImportAccount.tsx

https://github.com/iron-fish/node-app/assets/5459049/f0f318d8-b7cc-4f3d-99c3-d31ba3f3eb90

fix(node-app): Accept encoded bech32 files for import

---

electron/contextBridge/AccountManagerContext.ts
electron/ironfish/AccountManager.ts
src/data/DemoAccountsManager.ts
src/hooks/accounts/useAccount.ts
src/routes/Account/Settings/Settings.tsx
types/IronfishManager/IIronfishAccountManager.ts

https://github.com/iron-fish/node-app/assets/5459049/cc53f882-450d-43f4-9b62-49b1e51fda86

feat(node-app): Enable name updates for accounts

---

electron/common/initStorage.ts
electron/storage/AddressBookStorage.ts
src/routes/AddressBook/AddressBook.tsx

* Cascade custom errors from storage layers
* Show error toast if duplicate public address in address book

fix(node-app): Show error toast when adding duplicate public address

---

src/routes/Account/Keys/Keys.tsx

Spoke with @skylarrichard123 this link was intended to link to blog post, but that hasn't been written yet. Removing the link for now.

feat(ifl-1203): remove broken link account keys

---

src/routes/AddressBook/AddressDetails/ContactSettings.tsx

fix: Update copy on Remove Contact modal

---

README.md

Remove in development warnings from README.

chore(node-app): Update release instructions in README

---

electron/ironfish/IronFishManager.ts
src/routes/NodeOverview/NodeStatus.tsx
types/NodeStatusResponse.ts

feat(node-app): Show head hash and head sequence in overview

---

electron/common/UpdateManager.ts

Fixes update server URL due to SSL cert issue with the previous one.

fix: Update server URL

---

electron/ironfish/SnapshotManager.ts
src/components/Snapshot/SnapshotStatusModal.tsx
src/data/DemoSnapshotManager.ts

Fixes a few language issues in the Snapshot dialog.
Fixes IFL-1159
Fixes IFL-1158

Fix language tweaks in the Snapshot dialog

---

src/routes/AddressBook/AddContactModal.tsx

Fixes a language issue with the Add Contact dialog.
Fixes IFL-1149

Add period to Add Contact modal

---

src/routes/Account/Settings/Settings.tsx

Fixes language issues on the Remove Account dialog.
Fixes IFL-1147

Fix language issues on the Remove Account dialog

---

src/routes/Onboarding/CreateAccount/CreateStep.tsx
src/routes/Onboarding/CreateAccount/ValidateStep.tsx

Fixes the language issues on the Create Account dialog.
Fixes IFL-1142
Fixes IFL-1143

Fix language tweak issues on Create Account dialog

---

src/routes/Onboarding/ImportAccount.tsx

Adds periods to text on the Import Account dialog.
Fixes IFL-1144
Fixes IFL-1145

Fix language tweak issues on the Import screen

---

src/routes/Account/Overview/Transactions/Transactions.tsx

Improves the wording of the placeholder text on the no-transactions view.
Fixes IFL-1695

Fix transactions placeholder text

---

electron/contextBridge/IronfishManagerContext.ts
electron/ironfish/IronFishManager.ts
electron/storage/UserSettings.ts
src/data/DemoDataManager.ts
src/routes/NodeOverview/NodeOverview.tsx
src/routes/NodeOverview/NodeSettings/UserSettings.tsx
types/IronfishManager/IIronfishManager.ts
types/UserSettings.ts

Add option to open a different data directory in the node app

Add User Settings and option to change dataDir in app

---

electron/ironfish/AccountManager.ts

Fixes account import by deferring import logic to `decodeAccount` from Ironfish SDK.

Fix account import

---

README.md

I noticed a few typos and grammar errors while reading through the README. Figured I'd create a PR to fix some of them :)

Fix README typos and grammar.

---

electron/ironfish/IronFishManager.ts
electron/ironfish/TransactionManager.ts
package.json
src/components/Navbar/StatusBar/NodeSyncStatus.tsx
src/data/DemoNodeManager.ts
types/NodeStatusResponse.ts
types/Peer.ts
yarn.lock

Upgrade the SDK to 1.15.0 to pull in some fixes for account importing.

Bump SDK to 1.15.0
