electron/ironfish/IronFishManager.ts
- Disabled workers in worker pool
Problem is in wrong path to `worker.js`
[`getWorkerPath`](https://github.com/iron-fish/ironfish/blob/6769ec16520298e2fdd6313d71f6df8889989d6e/ironfish/src/workerPool/worker.ts#L289) return wrong path to this file
=> IRO-2679 Fixed errors on Iron Fish node start.

package.json, yarn.lock
improvements for 
[IRO-2692 auto complete behaviour](https://linear.app/ironfish/issue/IRO-2692/auto-complete-behaviour)
[IRO-2683 Dark mode - buttons should not have a hover state (other than the disabled icon) while syncing.](https://linear.app/ironfish/issue/IRO-2683/dark-mode-buttons-should-not-have-a-hover-state-other-than-the)
=> Update ui-kit version

src/routes/Send/Send.tsx
The application crash when clear input on "Send $IRON"
Steps to reproduce:
1. Go to "Send$IRON"
2. Clear input
Actual result:
Application crash
```
uncaught Error: invalid decimal value (argument="value", value="", code=INVALID_ARGUMENT
```
After fix:
As we see the input is empty and application still functional
=> Fix application crash when clear input while send $IRON

src/routes/Onboarding/CreateAccount/CreateStep.tsx, src/routes/Onboarding/ImportAccount.tsx
The mnemonic phrase should not be separated by commas they should be separated by spaces only.
**Reason 1:**
People want to save the phrases in the same format as they will be used during import
**Reason 2:**
it is an accepted standard used on other wallets Keplr, Metamask, Sui Wallet etc...
**Reason 3:**
The Ironfish CLI returns mnemonics separated by spaces only and customers expect just copy phrases and do not want to edit something.
Example during export:
```
root@test:~# ironfish wallet:export --mnemonic
Detected Language as 'English', exporting:
aware matrix planet quick eyebrow tray limb melt daring tray home robust describe spike hire father remind rabbit horror sight caution oil carry north
```
As we can see here also used just space
=> Do not use commas while copy mnemonic

README.md
lots of people are finding the wallet app on github and trying to install and use it as we launch mainnet.
=> adds 'in development' warning to top of README

src/providers/DataSyncProvider.tsx
During app onboarding, this was throwing an exception because node is not started and therefore no status can be retrieved.
=> fix: DataSyncProvider exeception fix

electron/ironfish/TransactionManager.ts, src/data/DemoTransactionsManager.ts, src/routes/Transaction/TransactionOverview.tsx, types/Transaction.ts
=> feat(ifl-900): updates transaction view for outputs to show owner instead of sender

forge.config.js
Not sure is that valid to do like this, but windows require url for icon that will be shown in uninstall manager and in some other places.
=> Add icon url for windows.

electron/ironfish/IronFishManager.ts, src/components/Navbar/StatusBar/NodeSyncStatus.tsx, src/components/Navbar/StatusBar/StatusItem.tsx, src/components/Navbar/StatusBar/index.tsx, src/components/SyncWarningMessage.tsx, src/providers/DataSyncProvider.tsx, types/NodeStatusResponse.ts
This PR does three things:
1. Returns account info in the status request to the node
2. Updates the Warning message to display when either the chain isn't synced OR an account isn't synced. This is the lowest code change method of handling this functionality.
3.  Updates the general syncing tab to display syncing info when imported accounts are being synced.
We can split these into separate PRs if the code change is too much.
=> feat(ifl-911): add account syncing status and warnings

electron/ironfish/AccountManager.ts, electron/ironfish/IronFishManager.ts, src/data/DemoAccountsManager.ts, types/IronfishManager/IIronfishAccountManager.ts
There is code in the RPC method for importing an account that is important for account initialization. Instead of calling methods directly from node, I use the RPC interface for importing account.
Create account test works, where account head is immediately moved to chain head:
https://github.com/iron-fish/node-app/assets/26990067/040dbc7c-2fb1-48eb-80c5-c47f0da3518b
Import account also works still with rescan occurring as expected:
=> feat(ifl-891): fix create account to have correct chain head

electron/ironfish/AccountManager.ts, electron/ironfish/IronFishManager.ts, src/data/DemoAccountsManager.ts, types/IronfishManager/IIronfishAccountManager.ts
Using the RPC for account creation fails at the onboarding screen because the node is in an uninitialized state. I will revert this and add code to manually start the rescan.
=> Revert "feat(ifl-891): fix create account to have correct chain head"

electron/ironfish/AccountManager.ts
Previously, if you onboarded to ironfish via node-app, the account birthday of the newly created account is null, meaning the entire chain has to be rescanned to show up to date status.
This handles that issue, it also uses the local chain head if syncing if chain has already occurred.
Defaults on any issue to `createdAt=null` meaning chain scan will occur.
=> feat(ifl-994): account birthday on creation for better onboarding

electron/ironfish/IronFishManager.ts
`IRONFISH_DATA_DIR="~/.nodeapp" yarn start:dev`
or
```
export IRONFISH_DATA_DIR="~/.nodeapp" 
yarn start:dev 
```
=> fix: ironfish datadir changeable by env var

.gitignore, package.json, src/components/PasswordField.tsx, src/components/Search&Sort/SortSelect.tsx, src/components/TransactionStatusView.tsx, src/hooks/node/useNodeStatus.ts, src/routes/Accounts/AccountTabs/Keys.tsx, src/routes/Accounts/Accounts.tsx, src/routes/AddressBook/AddressBook.tsx, src/routes/NodeOverview/NodeOverview.tsx, src/routes/NodeOverview/NodeResources.tsx, src/routes/NodeOverview/NodeSettings.tsx, src/routes/NodeOverview/NodeSettings/NodeSettings.tsx, src/routes/NodeOverview/NodeSettings/NodeWorkersSelect.tsx, src/routes/NodeOverview/NodeSettings/index.tsx, src/routes/NodeOverview/NodeStatus.tsx, src/routes/Receive/ReceiveMoney.tsx, yarn.lock
Made node settings page use grid for items layout.
Use select for node workers.
Added tooltip for node workers with message from sdk source.
Default value is still -1 but now its displayed as `auto-detect`.
=> (IFL-925) Use select box for node workers in settings.

src/routes/Accounts/AccountTabs/Keys.tsx, src/routes/Onboarding/CreateAccount/CreateStep.tsx, src/routes/Onboarding/CreateAccount/ValidateStep.tsx, src/routes/Onboarding/ImportAccount.tsx
Removes the info tooltip on the mnemonic view. IMO, any content that we may want to add behind a tooltip should just go below heading and always be visible.
Note that currently, the icon is there but there is no actual tooltip content.
=> [IFL-912] Remove info icon on mnemonic view

electron/contextBridge/SnapshotManagerContext.ts, electron/ironfish/SnapshotManager.ts, src/components/Navbar/StatusBar/SnapshotRequirement.tsx, src/components/Snapshot/SnapshotDownloadModal.tsx, src/components/Snapshot/SnapshotStatusModal.tsx, src/data/DemoSnapshotManager.ts, src/providers/DataSyncProvider.tsx, src/providers/SnapshotProvider.tsx, src/routes/SnapshotFlow.tsx, types/IronfishManager/IIronfishSnapshotManager.ts
This PR does a few things:
1. Allows user to decline snapshot, this was an easier change because of how integrated the snapshot system is into the user flow (instead of making the snapshot an optional flow).
2. On decline, starts the node/peer network and begins syncing
3. Modal opens immediately after snapshot manifest is retrieved, rather than chain being initialized
4. Snapshot modal is not dismissible
Cancel download/Sync flow:
https://github.com/iron-fish/node-app/assets/26990067/8857bcd1-a69a-4c01-b117-742ffcd58814
Download complete flow:
https://github.com/iron-fish/node-app/assets/26990067/59462bd2-4750-4b11-bd83-eae0c5e9aa59
=> feat(ifl-996): snapshot optional modal

electron/common/UpdateManager.ts, electron/contextBridge/IronfishManagerContext.ts, electron/ironfish/IronFishManager.ts, src/components/FirstRunTelemetryModal.tsx, src/components/SwitchToggle.tsx, src/data/DemoDataManager.ts, src/data/DemoNodeSettingsManager.ts, src/data/DemoUpdateManager.ts, src/routes/NodeOverview/NodeSettings/NodeSettings.tsx, src/routes/PageLayout.tsx, types/IronfishManager/IIronfishManager.ts
Displaying modal on first run.
Set telemetry enabled by default if it wasn't set.
Added node settings to enable telemetry.
=> (IFL-934) Add check for first run and ask for telemetry.

package.json, yarn.lock
This SDK version brings slight performance increases, and also the spend witness change will reduce the likelihood that transactions become invalid due to forking.
=> Update SDK to 1.3.0

electron/contextBridge/IronfishManagerContext.ts, electron/ironfish/IronFishManager.ts, src/data/DemoDataManager.ts, src/routes/Initializing.tsx, types/IronfishManager/IIronfishManager.ts
Uses `isFirstRun` from `sdk.internal.config` to determine if we should prompt for telemetry.
Previously telemetry was always prompted for during startup.
https://github.com/iron-fish/node-app/assets/26990067/99d2f41b-497d-41d9-b654-5445140144da
=> fix: bypass telemetry after initial selection

electron/common/initHandlers.ts, electron/contextBridge/AccountManagerContext.ts, electron/contextBridge/AssetManagerContext.ts, electron/contextBridge/ErrorManagerContext.ts, electron/contextBridge/IronfishManagerContext.ts, electron/contextBridge/NodeSettingsManagerContext.ts, electron/contextBridge/SnapshotManagerContext.ts, electron/contextBridge/StorageContext.ts, electron/contextBridge/TransactionManagerContext.ts, electron/contextBridge/UpdateManagerContext.ts, electron/contextBridge/util.ts
Error handling does not work at all between the main process and renderer process.
When using IPC between the main process and renderer process for Electron, promises cannot handle custom error objects and therefore exception traces are lost between the caller and callee. The serializer in the engine that runs JS breaks down with these custom error objects; nothing can catch these exceptions so the error is lost in translation.
To mitigate this issue, this code change includes a work around to always resolve error responses into a JSON object where an `error` field is set to true. If available, the `name`, `message`, and `stack` are set as well. If the receiving end gets an object with `error` being defined and truthy, the renderer process then creates a rejected error with appropriate …
=> feat(node-app): Catch errors and abstract into a resolved error response

.github/workflows/publish-prod.yaml
OSX signing enabled using:
https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions
https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
https://www.rocketride.io/blog/macos-code-sign-notarize-electron-app
https://developer.apple.com/help/account/create-certificates/create-developer-id-certificates/
Note that the cert needed was a:
"Developer ID Application" cert (that is what is now stored in GHA).
=> feat(ifl-1074): add signing yaml for OSX production build

electron/contextBridge/IronfishManagerContext.ts, electron/ironfish/IronFishManager.ts, src/components/ConfirmModal.tsx, src/components/ErrorMessagesModal.tsx, src/data/DemoDataManager.ts, src/routes/Accounts/AccountTabs/Settings.tsx, src/routes/NodeOverview/NodeSettings/NodeSettings.tsx, types/IronfishManager/IIronfishManager.ts
- Adds a `ConfirmModal` component (will be reused for account deletion).
- Uses that component for confirming node reset.
- Updates `IronFishManager` to have `resetNode` method callable from frontend.
- onConfirm will reset the node and restart the app
https://github.com/iron-fish/node-app/assets/26990067/02034166-59b1-4eba-a38f-6f29473c8589
=> feat(ifl-1047): reset node and confirm modal

electron/ironfish/TransactionManager.ts
The transaction list view does not show the first page correctly if there is a 0 offset in a single page for a single record.
If an account has one transaction:
* The loop will stream element
* The offset check will continue to the next iteration
* The stream won't have any records
* The transaction won't get returned to the caller
=> fix(node-app): Fix offset in pagination for single record

electron/ironfish/AccountManager.ts, src/components/AccountsSelect.tsx, src/data/DemoAccountsManager.ts, src/routes/Accounts/AccountPreview.tsx, src/routes/Accounts/AccountTabs/Keys.tsx, src/routes/Accounts/AccountTabs/Overview/OverviewBalance.tsx, src/routes/Receive/ReceiveMoney.tsx, types/Account.ts, types/CutAccount.ts
- Fixes account details page with view only
- disables `Send` button for view only accounts in various places
- Removes view only accounts from send addresses
=> feat(ifl-1094): view only account support

src/routes/Accounts/AccountTabs/Overview/SearchTransactions.tsx
Previously if change note is present, it will only display the memo of that note (if a change note is present). This tries to grab non-change note if no other memo is found.
=> fix(ifl-1075): display memo of non-change note if present

src/routes/Send/SendFlow/ConfirmStep.tsx
Fixes bug that doesn't display newly added contact in send menu
https://github.com/iron-fish/node-app/assets/26990067/8c03ac21-bb2c-43bb-a424-ae1bdc0d1068
=> fix(ifl-1079): add contact in send menu bug

electron/ironfish/AccountManager.ts
All of the decoded data is present, there is no reason to generate from the spending key. Also removed the conditional since the spending key won't be present for view only accounts.
=> fix: support view only account import

package.json, webpack/common/rules.js, yarn.lock
The migrations load their ID and name dynamically using `__fileName`. This doesn't work when the files are bundled together using webpack, and it's not easy to separate webpack from electron-forge, so for now we can overwrite `__filename` in the migration files with the original filename.
We should probably consider fixing this in the SDK to embed the name and ID directly in the migrations rather than loading them dynamically, but this will work for now without an SDK deployment.
=> Fix migration ID and name loading in webpack

src/routes/Account/Overview/Transactions/Transactions.tsx
- Reduces transaction row's border radius to 4px
- Adds "—" as the default content for memos with no content
- Simplifies media query that was causing flash of incorrect styling
=> chore(transactions list): Tweak border radius, simplify media query

src/components/ViewOnlyChip/ViewOnlyChip.tsx, src/data/DemoAccountsManager.ts, src/routes/Account/AccountDetails.tsx, src/routes/Accounts/AccountPreview.tsx, src/routes/Accounts/Accounts.tsx
Adds "View Only" chip + tooltip indicator for view-only accounts.
=> feat: Add view-only chip indicator

src/routes/Send/SendFlow/ConfirmStep.tsx
=> fix(node-app): Show total for $IRON properly in confirmation modal

webpack/common/rules.js
The initial fix was merged in https://github.com/iron-fish/node-app/pull/328, and this branch updates the path separators so the fix works properly when built on Windows as well.
=> fix: Fix corrupting Windows data directory on initial load

.github/workflows/publish-prod.yaml
Uses self hosted runner for m1 build. Eventually this will be possible without a self hosted runner (Q4 2023):
https://github.com/github/roadmap/issues/528
I manually tested by changing to `on: push`, working succesfully.
=> feat: mac arm64 self hosted runner

electron/contextBridge/IronfishManagerContext.ts, electron/ironfish/IronFishManager.ts, src/data/DemoDataManager.ts, src/routes/Transaction/TransactionOverview.tsx, src/utils/constants.ts, types/IronfishManager/IIronfishManager.ts
Adds block explorer links to
1. Transaction
2. Block
https://github.com/iron-fish/node-app/assets/26990067/0a3e3b80-3545-4dcf-a506-d32a19e7e97c
=> feat(ifl-1096): block explorer links in transaction overview

electron/ironfish/IronFishManager.ts
Instead of migrating if _not_ on mainnet, migrate _only_ testnet -> mainnet
=> chore(ifl-1131): migrate only if on testnet

src/routes/Account/Keys/Keys.tsx
The JSON extension is only needed if a JSON export is selected for the keys. Otherwise, omit the extension and let the downloader handle.
=> fix(node-app): `.json` extension added only if JSON export

electron/ironfish/IronFishManager.ts
If a data directory does not contain `enableTelemetry`, the application will set it to true when initializing. We shouldn't do that.
=> fix(node-app): Don't automatically set telemetry to true

src/routes/NodeOverview/NodeSettings/NodeSettings.tsx
Updates the copy on the Reset Node modal to what's on the Linear ticket.
=> fix: Update copy on Reset Node modal

electron/common/UpdateManager.ts, electron/contextBridge/UpdateManagerContext.ts, package.json, src/data/DemoUpdateManager.ts, src/providers/ReleaseNotesProvider.tsx, src/routes/Updates/Updates.tsx, types/IUpdateManager.ts
- Adds `"_arm64"` to the platform sent to the update server if on an arm64 architecture.
- Updates the ReleaseNotesProvider so that it doesn't rely on calling `checkForUpdates()` in order to get the latest release notes.
- On the updates page, if the user is on an old version, it adds a link to download the latest version on the latest release notes tag.
=> fix: Don't check for updates to render updates page + add latest version download link

src/routes/Transaction/TransactionOverview.tsx
This transaction was indeed coming from airdrop account.
Assumes single sender for transaction.
=> fix: sender incorrect address for incoming transaction

electron/common/index.ts
Fixes issues on Mac OS where user can close the window but then not reopen it from the task bar.
=> fix(Mac OS): Re-open window when clicking task bar icon

src/components/Snapshot/SnapshotDownloadModal.tsx
There's no loading state associated with this.
=> feat(node-app): Remove loading spinner from `Sync from Peers`

package.json, yarn.lock
Bumps ui-kit version to fix icon in top right of screen.
=> chore: Bump ui-kit to version 1.1.12

electron/ironfish/AccountManager.ts, electron/ironfish/TransactionManager.ts, package.json, yarn.lock
- Bumps @ironfish/sdk to 1.5.0
- Updates `node.wallet.send` signature
- Fixes TS type
=> chore: Bump @ironfish/sdk version

README.md
The locally packaged macOS app won't run without codesigning. This PR adds instructions to the README for performing adhoc codesigning without any certificates required.
=> Add adhoc codesigning instructions to README

.github/workflows/publish-prod.yaml, electron/ironfish/AbstractManager.ts, electron/ironfish/AccountManager.ts, electron/ironfish/AssetManager.ts, electron/ironfish/IronFishManager.ts, electron/ironfish/NodeSettingsManager.ts, electron/ironfish/SnapshotManager.ts, electron/ironfish/TransactionManager.ts, package.json, src/data/DemoDataManager.ts, yarn.lock
Updates the Iron Fish SDK in the Node App to v1.9.0. This also syncs the rust-nodejs package version with that of the SDK, which reduces the bundle size by around 50MB.
=> Update Node App SDK to v1.9.0

.github/workflows/publish-prod.yaml, electron/common/UpdateManager.ts, package.json, scripts/demo-update-server.js
The update server URL had two slashes, which caused the Windows auto-update code to error. This uses the URL constructor to parse the URL, which is a bit more resistant to extra slashes. Also added a few more logs to the auto-updater to track when it checks for updates and whether an update is available or no, and added a mock update server to the scripts folder for use when testing auto-updating in the future.
Also added a network timeout to yarn install on the Windows build, since it was failing a decent amount.
=> Update update server URL to fix Windows auto-updating

electron/common/initHandlers.ts, electron/common/initStorage.ts, electron/contextBridge/util.ts
If an error is thrown as a result of executing a handler on the main process, a response is returned across the IPC bridge with an object containing `{ error: true }`. Then on the renderer side, in the `invoke` util, the function watches for truthy values of `error`, and if it sees one, it throws the response.
However, in the snapshot manager, we return objects that include an `error` field, which ends up getting thrown by the `invoke` util. This is probably not intended behavior -- I'd lean toward establishing a pattern where unrecoverable or unintended errors are thrown, and recoverable errors are returned on the response body.
To avoid this, I wrapped successful responses in `{ error: false, data: object }` and returned the response body on the `data` field instead.
=> Wrap IPC response data in object

electron/ironfish/SnapshotManager.ts, src/components/Navbar/StatusBar/SnapshotRequirement.tsx, src/components/Navbar/StatusBar/index.tsx, src/components/Snapshot/SnapshotDownloadModal.tsx, src/components/Snapshot/SnapshotStatusModal.tsx, src/routes/PageLayout.tsx
Fixes a few problems with error display when downloading snapshots:
* Errors that happen during `start` would cause the download modal to close anyway without displaying the error. Now the modal stays open until a choice is made.
* Errors from `checkPath` weren't actually set.
* Removed code for choosing a path -- we can add that as a feature in the future, but the code path didn't work and downloaded to the node's temp directory instead.
* Cleaned up the grammar on displayed error messages
* There were two instances of the SnapshotDownloadModal -- This doesn't seem to be necessary in the current design, from what I can tell.
* Fixed disabling the button while the loading spinner is active
* Removed some unused props from SnapshotDownloadModal
=> Fix display of snapshot errors

forge.config.js, package.json
The 1.0.2 build was including node_modules and devDependencies, which was also causing code signing to fail on macOS. I'm not certain why it would be happening now and not on prior builds, but I suspect the packageAfterPrune step of the build might have been causing it. Removing this step and triggering a build caused the build to complete successfully.
=> Remove npm install from packageAfterPrune

src/routes/Send/Send.tsx
The total amount + fees was being compared to the balance of the chosen asset, but fees should only ever apply to the $IRON balance. This changes the check to error in these cases:
* $IRON balance is less than amount + fee if $IRON is chosen
* $IRON balance is less than fee if $IRON is not chosen
* chosen asset balance is less than amount
=> Fix calculation of fees in multi-asset transactions

electron/ironfish/IronFishManager.ts, forge.config.js, package.json, src/data/DemoNodeManager.ts, src/routes/NodeOverview/NodePeers.tsx, types/Peer.ts, yarn.lock
Removes react-flag-kit and the "country" field on Peers for now, since we're not actually displaying it in the production app. This also has the side effect of fixing a console complaint about a typo in the dev environment's content security policy, which I don't think we need.
Fixes IFL-1692
=> Remove react-flag-kit

electron/ironfish/IronFishManager.ts, src/routes/NodeOverview/NodeSettings/NodeSettings.tsx
Resets accounts when resetting the node. If this is not done, the app gets stuck in an unusable state due to accounts being ahead of the chain.
=> fix: Reset accounts when resetting node via settings

src/routes/Send/Send.tsx
=> tweak: Vertically stack the input and asset label in the send asset screen

electron/ironfish/IronFishManager.ts
I've seen a few crashes with the error message `getaddrinfo ENOTFOUND 1.main.bn.ironfish.network`. I think the SDK handles errors properly in WebSocketConnection and WebRTCConnection, since I don't think we've ever seen this from the CLI. I found this DNS lookup that seems likely to be the culprit, and since we don't use it for anything, it's easy to remove.
Fixes IFL-1693
=> Remove unused dns lookup

electron/common/initStorage.ts, electron/storage/AddressBookStorage.ts, src/hooks/addressBook/useAddressBook.ts, src/routes/AddressBook/AddressBook.tsx
Fixes issue that was causing the Address Book to break because `initStorageCallbacks` was causing the IPC bridge to send promises over the wire, which is not allowed.
=> Fix initStorageCallbacks causing ipc handler to try to return unserializable data

src/routes/NodeOverview/NodeStatus.tsx
If the user doesn't have a node name set, show a default label for the Node Overview page
=> Add default label if there's no node name

.github/workflows/publish-prod.yaml
Mac x64 builds were erroring out when using electron/rebuild -- this installs setuptools as part of the build process on mac x64 runners to work around the issue.
=> Fix Mac x64 builds by installing setuptools

src/App.tsx, src/components/Navbar/index.tsx, src/routes/PageLayout.tsx, src/routes/Upgrade.tsx
Adds a bar to the top of the app informing users to uninstall and redownload the app. This isn't ready to merge and ship until we've actually published the new app and updated the website though.
I wanted to put the bar at the very top level of the app, so had to shuffle around the layout a bit. Ideally even if the app eventually gets too outdated to initialize the Iron Fish SDK, the bar will still appear on all screens.  
Here's what it looks like:
Fixes IFL-1829
Fixes IFL-1834
=> Add required upgrade bar to top of app
